[tool.poetry]
name = "buttontracker"
version = "0.1.0"
description = ""
authors = ["alexo <the.onga@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
pygame = "1.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
